swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
      # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching all transactions
      parameters:
        - in: body
          name: body
          description: Fetch all transactions
          required: true
          schema:
            $ref: '#/definitions/LoginResponse'
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successully
          schema:
            $ref: '#/definitions/FetchAllTransactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile/transactions/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a specific transaction
      parameters:
        - in: body
          name: body
          description: Fetch a specific transaction
          required: true
          schema:
            $ref: '#/definitions/FetchTransaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction retrieved successully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile/transactions/{id}/category:
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for editing a transaction's category
      parameters:
        - in: body
          name: body
          description: Edit transaction category
          required: true
          schema:
            $ref: '#/definitions/EditTransactionCategory'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction category edited successfully
          schema:
            $ref: '#/definitions/EditTransactionCategory'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile/transactions/{id}/notes:
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for editing a transaction's notes
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/FetchTransactionNotes'
      produces:
        - application/json
      responses:
        '200':
          description: Note edited successfully
          schema:
            $ref: '#/definitions/FetchTransactionNotes'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  FetchAllTransactions:
    type: object
    properties:
      transaction-id:
        type: integer
      transaction-desc:
        type: string
      transaction-amount:
        type: integer
  FetchTransaction:
    type: object
    properties:
      transaction-id:
        type: integer
  TransactionResponse:
    type: object
    properties:
      transaction-id:
        type: integer
      transaction-desc:
        type: string
      transaction-amount:
        type: integer
      transaction-category:
        type: string
      transaction-notes:
        type: string
  EditTransaction:
    type: object
    properties:
      transaction-id:
        type: integer
      transaction-desc:
        type: string
      transaction-amount:
        type: integer
      transaction-category:
        type: string
  EditTransactionCategory:
    type: object
    properties:
      transaction-id:
        type: integer
      transaction-category:
        type: string
  FetchTransactionNotes:
    type: object
    properties:
      transaction-id:
        type: integer
      transaction-notes:
        type: string